/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelo.cls_trabajadores;
import Modelo.cls_finca;
import Modelo.cls_cultivos;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author AP-SE105-01
 */
public class frm_finca extends javax.swing.JFrame {

    /**
     * Creates new form frm_finca
     */
    LinkedList<cls_trabajadores> obj_works = new LinkedList<>();
    LinkedList<cls_finca> obj_finca = new LinkedList<>();
    LinkedList<cls_cultivos> obj_cultivo = new LinkedList<>();
    boolean bln_sw;
    int int_posicion;

    public frm_finca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_nit = new javax.swing.JTextField();
        txt_nombrefinca = new javax.swing.JTextField();
        txt_ubicacion = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt_codigo = new javax.swing.JTextField();
        txt_nombrecultivo = new javax.swing.JTextField();
        txt_contacto = new javax.swing.JTextField();
        txt_nitfinca = new javax.swing.JTextField();
        txt_cargo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        txt_codigocultivo = new javax.swing.JTextField();
        txt_nombretrabajador = new javax.swing.JTextField();
        txt_descripcioncultivo = new javax.swing.JTextField();
        txt_produccion = new javax.swing.JTextField();
        txt_cod_trabajador = new javax.swing.JTextField();
        txt_labores = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        txt_propietario = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        btn_consultaasociados = new javax.swing.JButton();
        btn_consultar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 36)); // NOI18N
        jLabel1.setText("GESTIÓN DE FINCAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txt_nit.setBorder(javax.swing.BorderFactory.createTitledBorder("Nit"));
        txt_nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nitActionPerformed(evt);
            }
        });

        txt_nombrefinca.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        txt_nombrefinca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombrefincaActionPerformed(evt);
            }
        });

        txt_ubicacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Ubicacion"));

        txt_correo.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo"));
        txt_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correoActionPerformed(evt);
            }
        });

        txt_codigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));
        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });

        txt_nombrecultivo.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        txt_nombrecultivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombrecultivoActionPerformed(evt);
            }
        });

        txt_contacto.setBorder(javax.swing.BorderFactory.createTitledBorder("Contacto"));
        txt_contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactoActionPerformed(evt);
            }
        });

        txt_nitfinca.setBorder(javax.swing.BorderFactory.createTitledBorder("Nit finca"));
        txt_nitfinca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nitfincaActionPerformed(evt);
            }
        });

        txt_cargo.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargo"));
        txt_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cargoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setText("Módulo Finca");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setText("Módulo Trabajadores");

        btn_actualizar.setBackground(new java.awt.Color(204, 255, 255));
        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(204, 255, 255));
        jButton10.setText("Agregar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(204, 255, 255));
        jButton11.setText("Actualizar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(204, 255, 255));
        jButton13.setText("Limpiar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        txt_codigocultivo.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));
        txt_codigocultivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigocultivoActionPerformed(evt);
            }
        });

        txt_nombretrabajador.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        txt_nombretrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombretrabajadorActionPerformed(evt);
            }
        });

        txt_descripcioncultivo.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion"));
        txt_descripcioncultivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcioncultivoActionPerformed(evt);
            }
        });

        txt_produccion.setBorder(javax.swing.BorderFactory.createTitledBorder("Producción(KG)"));
        txt_produccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_produccionActionPerformed(evt);
            }
        });

        txt_cod_trabajador.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo trabajador"));
        txt_cod_trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_trabajadorActionPerformed(evt);
            }
        });

        txt_labores.setBorder(javax.swing.BorderFactory.createTitledBorder("Labores"));
        txt_labores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_laboresActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setText("Módulo Cultivos");

        jButton14.setBackground(new java.awt.Color(204, 255, 255));
        jButton14.setText("Asociar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(204, 255, 255));
        jButton15.setText("Limpiar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        txt_propietario.setBorder(javax.swing.BorderFactory.createTitledBorder("Propietario"));
        txt_propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_propietarioActionPerformed(evt);
            }
        });

        btn_agregar.setBackground(new java.awt.Color(204, 255, 255));
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_limpiar.setBackground(new java.awt.Color(204, 255, 255));
        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_consultar.setBackground(new java.awt.Color(204, 255, 255));
        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        btn_consultaasociados.setBackground(new java.awt.Color(204, 255, 204));
        btn_consultaasociados.setText("Consultar");
        btn_consultaasociados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultaasociadosActionPerformed(evt);
            }
        });

        btn_consultar1.setBackground(new java.awt.Color(204, 255, 255));
        btn_consultar1.setText("Consultar");
        btn_consultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_cod_trabajador, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txt_codigocultivo)
                            .addComponent(txt_descripcioncultivo))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_nombrecultivo, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_produccion))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(txt_labores, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_consultar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nombretrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nitfinca))
                    .addComponent(txt_cargo, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(93, 93, 93))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_consultaasociados, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton11)
                                .addGap(18, 18, 18)
                                .addComponent(jButton13)))
                        .addContainerGap(93, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nombrefinca, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_correo)
                                        .addGap(80, 80, 80))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_propietario)
                                .addGap(80, 80, 80)))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(btn_consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(109, 109, 109))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombrefinca, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_correo)
                            .addComponent(txt_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(txt_propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(btn_consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel3)
                    .addComponent(txt_nombretrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nitfinca)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consultaasociados, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_codigocultivo, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_nombrecultivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_descripcioncultivo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_produccion, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cod_trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_labores, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nitActionPerformed

    private void txt_nombrefincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombrefincaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombrefincaActionPerformed

    private void txt_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correoActionPerformed

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoActionPerformed

    private void txt_nombrecultivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombrecultivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombrecultivoActionPerformed

    private void txt_contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactoActionPerformed

    private void txt_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cargoActionPerformed

    private void txt_nitfincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nitfincaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nitfincaActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        obj_finca.get(int_posicion).setStr_nombre(txt_nombrefinca.getText());
        obj_finca.get(int_posicion).setStr_ubicacion(txt_ubicacion.getText());
        obj_finca.get(int_posicion).setStr_correo(txt_correo.getText());
        obj_finca.get(int_posicion).setStr_propietario(txt_propietario.getText());
        JOptionPane.showMessageDialog(null, "Finca actualizada con éxito", "Actualizar", JOptionPane.INFORMATION_MESSAGE);  // TODO add your handling code here:
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 if (txt_nombretrabajador.getText().isEmpty()
                || txt_codigo.getText().isEmpty()
                || txt_nitfinca.getText().isEmpty()
                || txt_contacto.getText().isEmpty()
                || txt_cargo.getText().isEmpty()) {
            // Mostrar un mensaje de que todos los datos deben ser llenados
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.", "Campos Incompletos", JOptionPane.WARNING_MESSAGE);
        } else         obj_works.add(new cls_trabajadores(
                txt_codigo.getText(),
                txt_nombretrabajador.getText(),
                txt_nitfinca.getText(),
                txt_contacto.getText(),
                txt_cargo.getText()));
        JOptionPane.showMessageDialog(null, "Registrado con exito", "Registro", JOptionPane.INFORMATION_MESSAGE);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        bln_sw = false;
        int_posicion = 0;
        for (int i = 0; i < obj_works.size(); i++) {
            if (txt_nit.getText().equals(obj_works.get(i).getStr_codigo())) {
                bln_sw = true;
                int_posicion = i;
                break;
            }
        }
        if (bln_sw = false) {
            JOptionPane.showMessageDialog(null, "No se encontraron registros", "ERORR", JOptionPane.ERROR_MESSAGE);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        txt_codigo.setText("");
        txt_nombretrabajador.setText("");
        txt_nitfinca.setText("");
        txt_contacto.setText("");
        txt_cargo.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void txt_codigocultivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigocultivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigocultivoActionPerformed

    private void txt_nombretrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombretrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombretrabajadorActionPerformed

    private void txt_descripcioncultivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcioncultivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcioncultivoActionPerformed

    private void txt_produccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_produccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_produccionActionPerformed

    private void txt_cod_trabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_trabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_trabajadorActionPerformed

    private void txt_laboresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_laboresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_laboresActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        obj_cultivo.add(new cls_cultivos(
                txt_cod_trabajador.getText(),
                txt_nombrecultivo.getText(),
                txt_codigocultivo.getText(),
                txt_descripcioncultivo.getText(),
                txt_labores.getText(),
                txt_produccion.getText()));
        JOptionPane.showMessageDialog(null, "Asociado con exito", "Registro", JOptionPane.INFORMATION_MESSAGE);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        txt_cod_trabajador.setText("");
        txt_nombrecultivo.setText("");
        txt_codigocultivo.setText("");
        txt_descripcioncultivo.setText("");
        txt_labores.setText("");
        txt_produccion.setText("");      // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void txt_propietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_propietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_propietarioActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if (txt_nit.getText().isEmpty()
                || txt_nombrefinca.getText().isEmpty()
                || txt_ubicacion.getText().isEmpty()
                || txt_propietario.getText().isEmpty()
                || txt_correo.getText().isEmpty()) {
            // Mostrar un mensaje de que todos los datos deben ser llenados
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.", "Campos Incompletos", JOptionPane.WARNING_MESSAGE);
        } else {
            obj_finca.add(new cls_finca(
                    txt_nit.getText(),
                    txt_nombrefinca.getText(),
                    txt_ubicacion.getText(),
                    txt_propietario.getText(),
                    txt_correo.getText()));
            JOptionPane.showMessageDialog(null, "Finca registrada con exito", "Registro", JOptionPane.INFORMATION_MESSAGE);          // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarActionPerformed
    }

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        txt_nit.setText("");
        txt_nombrefinca.setText("");
        txt_ubicacion.setText("");
        txt_correo.setText("");
        txt_propietario.setText("");           // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        bln_sw = false;
        int_posicion = 0;

        for (int i = 0; i < obj_finca.size(); i++) {
            if (txt_nit.getText().equals(obj_finca.get(i).getStr_nit())) {
                bln_sw = true;
                int_posicion = i;
                break;
            }
        }

        if (bln_sw == false) {
            JOptionPane.showMessageDialog(null, "No se encontraron registros", "Consultar", JOptionPane.ERROR_MESSAGE);
            

        } else {
            txt_nit.setText(obj_finca.get(int_posicion).getStr_nit());
            txt_nombrefinca.setText(obj_finca.get(int_posicion).getStr_nombre());
            txt_ubicacion.setText(obj_finca.get(int_posicion).getStr_ubicacion());
            txt_correo.setText(obj_finca.get(int_posicion).getStr_correo());
            txt_propietario.setText(obj_finca.get(int_posicion).getStr_propietario());

        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_consultaasociadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultaasociadosActionPerformed
     String trabajadorID = JOptionPane.showInputDialog(null, "Ingrese el ID del trabajador:");

    if (trabajadorID != null && !trabajadorID.isEmpty()) {
        // Buscar el trabajador por el ID ingresado
        cls_trabajadores trabajadorEncontrado = null;

        for (cls_trabajadores trabajador : obj_works) {
            if (trabajador.getStr_codigo().equals(trabajadorID)) {
                trabajadorEncontrado = trabajador;
                break;
            }
        }

        if (trabajadorEncontrado != null) {
            String nombreTrabajador = trabajadorEncontrado.getStr_nombre();
            String nitFincaAsociada = trabajadorEncontrado.getStr_nitfinca();

            // Buscar el cultivo asociado al trabajador
            String nombreCultivoAsociado = null;

            for (cls_cultivos cultivo : obj_cultivo) {
                if (cultivo.getStr_cod_trabajador().equals(trabajadorID)) {
                    nombreCultivoAsociado = cultivo.getStr_nombre();
                    break;
                }
            }

            // Buscar la finca asociada al cultivo
            String nombreFincaAsociada = null;

            for (cls_finca finca : obj_finca) {
                if (finca.getStr_nit().equals(nitFincaAsociada)) {
                    nombreFincaAsociada = finca.getStr_nombre();
                    break;
                }
            }

            String mensaje = "Trabajador: " + nombreTrabajador + "\nCultivo Asociado: " + nombreCultivoAsociado + "\nFinca Asociada: " + nombreFincaAsociada;
            JOptionPane.showMessageDialog(null, mensaje, "Información del Trabajador", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "No se encontraron registros asociados al ID del trabajador ingresado.", "Sin Resultados", JOptionPane.WARNING_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "Debe ingresar un ID de trabajador válido.", "Entrada Inválida", JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_btn_consultaasociadosActionPerformed

    private void btn_consultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar1ActionPerformed
        bln_sw = false;
        int_posicion = 0;

        for (int i = 0; i < obj_cultivo.size(); i++) {
            if (txt_codigocultivo.getText().equals(obj_cultivo.get(i).getStr_codigocultivo())) {
                bln_sw = true;
                int_posicion = i;
                break;
            }
        }

        if (bln_sw == false) {
            JOptionPane.showMessageDialog(null, "No se encontraron registros", "Consultar", JOptionPane.ERROR_MESSAGE);
           //Inhabilita el boton de actualizar

        } else {
            txt_codigocultivo.setText(obj_cultivo.get(int_posicion).getStr_codigocultivo());
            txt_nombrecultivo.setText(obj_cultivo.get(int_posicion).getStr_nombre());
            txt_descripcioncultivo.setText(obj_cultivo.get(int_posicion).getStr_descripcion());
            txt_produccion.setText(obj_cultivo.get(int_posicion).getStr_produccion());
            txt_labores.setText(obj_cultivo.get(int_posicion).getStr_labores());
            txt_cod_trabajador.setText(obj_cultivo.get(int_posicion).getStr_cod_trabajador());

        }           // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_finca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_finca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_finca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_finca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_finca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_consultaasociados;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_consultar1;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txt_cargo;
    private javax.swing.JTextField txt_cod_trabajador;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_codigocultivo;
    private javax.swing.JTextField txt_contacto;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_descripcioncultivo;
    private javax.swing.JTextField txt_labores;
    private javax.swing.JTextField txt_nit;
    private javax.swing.JTextField txt_nitfinca;
    private javax.swing.JTextField txt_nombrecultivo;
    private javax.swing.JTextField txt_nombrefinca;
    private javax.swing.JTextField txt_nombretrabajador;
    private javax.swing.JTextField txt_produccion;
    private javax.swing.JTextField txt_propietario;
    private javax.swing.JTextField txt_ubicacion;
    // End of variables declaration//GEN-END:variables
}
